### PR TITLE
Swift 4 support

### PR DESCRIPTION
**Pull request by quanvo87**
## Checklist:

- [ ] I have submitted a [CLA form](https://github.com/IBM-Swift/CLA)
- [ ] If applicable, I have updated the documentation accordingly.
- [ ] If applicable, I have added tests to cover my changes.

### CODE REVIEW

**Comment by quanvo87** [comment]
https://swift.org/blog/swift-package-manager-manifest-api-redesign/

The rename puts the source files in a folder called `SSLService`. This is the default folder path Swift 4 PM looks for when trying to find the target. Without this, it fails. A custom target path can be defined but I thought changing the package's layout to use the default layout Swift 4 PM looks for was a better solution. Thoughts?

**Comment by quanvo87** [comment]
This will not work on Linux, working on fix.

**Comment by quanvo87** [comment]
The latest push compile on Linux, but breaks looking for [OpenSSL](https://github.com/IBM-Swift/OpenSSL). OpenSSL will need to be updated for Swift 4 support first. I'll also add Swift 4 Travis builds when this happens.

**Comment by youming-lin** [comment]
IBM-Swift/Kitura#1121

**Pull request merged**
