### PR TITLE
Feature request: let client compare self-signed server cert against local embedded version

### PR DESCRIPTION
**Pull request by kkieffer**
Added an optional URL with a path to a local DER-encocded certificate. When allowing self-signed certificates, the embedded certificate is loaded as an Anchor Certificate and validated using SecTrustEvaluateWithError()

## Description
For the user, the only interface change is an optional URL in the Configuration init() method. If not set, the previous behavior is maintained. When the URL is set to a file, and the user has allowed self-signed certificates and is a client, then during the SSLHandshake the server presented trust is validated against the embedded certificate.  The certificate must be a DER encoded X.509 certificate.

## Motivation and Context
I am using BlueSSLService on iOS to connect securely to a server that uses its own root certificate, but I would like to validate the certificate.  Previously, you can only accept any server supplied certificate, or the server certificate must be trusted by iOS.  (There's no way to programmatically add the certificate to iOS keychain, you must go through a process to have the user install from a browser).  If I have the public certificate of the server embedded in the app, I can use this feature to validate it.

## How Has This Been Tested?
This is an iOS feature only - not implemented on Linux. I verified that when the URL is set to nil, the behavior is unchanged - I can successfully connect to my server when self-signed is true, and I get an errSSLXCertChainInvalid error when self-signed is false.  If I embed by server certificate in the app and load it as follows

` let path = Bundle.main.url(forResource: "cert", withExtension: ".der")
`
Then it successfully establishes the SSL connection.  If I use a different (dummy) certificate, I again get the errSSLXCertChainInvalid error.

Note that in order to compile I needed to use

`swift build -Xswiftc "-target" -Xswiftc "x86_64-apple-macosx10.14"

because SecTrustEvaluateWithError is a 10.14 feature.

## Checklist:

- [ ] I have submitted a [CLA form](https://github.com/IBM-Swift/CLA)
- [ ] If applicable, I have updated the documentation accordingly.
- [ ] If applicable, I have added tests to cover my changes.

### CODE REVIEW

**Comment by billabt** [comment]
Any chance you can add a test using that case to _SSLServiceTests.swift_?

**Comment by kkieffer** [comment]
I added test test case to the SSLServiceTests.swift, but I noticed that the SSL option was turned off for Apple platforms. I turned it back on.  All tests are working correctly for me building locally on OSX with SSL, but the Travis CI seems to hang when the client connects.  Can you help?  Here's the last output before hang...

```
Test Case '-[SSLServiceTests.SSLServiceTests testSecureReadWriteEmbedded]' started.
Listening on port: 1337
Using embedded cert: file:///Users/travis/build/IBM-Swift/BlueSSLService/Tests/SSLServiceTests/certs/cert.der
Attempting to connect to host: 127.0.0.1:1337...
```

**Comment by kkieffer** [comment]
I changed the test order so the original test could be executed first, but it still hangs on connect. I suspect this might be an issue with the Travis CI environment. All tests pass for me locally on OSX 10.14.6.

**Comment by billabt** [comment]
@djones: Any insight on the CI failure?  Thanks.

**Comment by billabt** [comment]
Disable SSL when testing on macOS so that it passes CI.  This is a _definitely_ a CI problem.  After I merge, I'll test locally on macOS to ensure it passes the new test before doing the release.  Thanks for your patience...

**Comment by djones** [comment]
@billabt just FYI you have the wrong @djones here. I'm not part of this project.

**Comment by kkieffer** [comment]
Done.  Passing CI now.

**Comment by billabt** [comment]
@djones6: Can you take a look at the CI failure when we turn on testing for macOS? It passes locally but I want to make sure we’re dealing with a CI issue before I merge the changes. Thanks.

**Comment by djones6** [comment]
@billabt I'm afraid I am by no means an expert on this, but my guess would be that the hang is to do with unlocking the keychain.  I have successfully used a trick in the past in a headless environment (not Travis) which creates a new keychain (and unlocks it) prior to running the tests:
https://github.com/IBM-Swift/Kitura-Benchmarks/blob/master/Bench-Kitura-Core/scripts/ssl_setup.sh

You could add a script like this as `osx/before_tests.sh` which Package-Builder will then execute just before it runs `swift test`.

I'd be somewhat surprised however if this solves this issue, because we're successfully running Kitura's CI with SSL enabled in Travis without any such tricks.  Worth a try though.

**Comment by kkieffer** [comment]
It looks like the statements in @djones6 `ssl_setup.sh` script are already in the `osx/before_tests.sh` script. Is it possible Travis CI isn't running this script?

**Comment by djones6** [comment]
The Travis log shows that the script is running, and doesn't indicate there being any problems with it:
```
>> Testing Swift package...
security: SecKeychainDelete: The specified keychain could not be found.
Keychain SSLService.keychain does not exist.
SSLService.keychain created...
Keychain unlocked, ready to set timeout...
Keychain timeout set. Ready for import...
Keychain "SSLService.keychain" timeout=3600s
1 identity imported.
Import complete.  Ready for testing...
>> Completed osx pre-tests steps.
```
If this doesn't work, then I'm afraid I don't know. 

For the sake of this PR, the CI is sufficient to demonstrate that it builds successfully in each of the environments.  If we can also demonstrate that local testing of the feature is successful, I think that'll have to be good enough.

**Comment by billabt** [comment]
I agree.  I'll run the checks here to confirm.

**Comment by kkieffer** [comment]
Any issues running the checks?  Let me know if I can help.

**Comment by billabt** [comment]
@kkieffer Sorry I haven't merged this yet.  Spent a bit of time in the hospital and then a bit of recovery time.  I should be able to wrap it up this week.  Again, sorry...

**Comment by kkieffer** [comment]
No worries, sorry to hear you were in the hospital.

**Comment by kkieffer** [comment]
Any updates?

**Comment by billabt** [comment]
Sorry this took so long.  Ran into a problem when publishing on cocoa pods.  Had to change the _if available_ statement to include **tvOS 12.0** as well.  Also had to make changes to the Xcode project file (for those that use it) so that it can run the test when enabled.

It's now released as **Version 1.0.52** on both Github and Cocoapods.

**Comment by kkieffer** [comment]
Awesome - thank you!

**Pull request merged**
